version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  test:
    build: .
    command: yarn test
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: downforacross_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
volumes:
  db-data:
